services:
  core-db:
    image: postgres:15-alpine
    container_name: core-db
    environment:
      POSTGRES_DB: banking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kimquan1
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - banking-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d banking_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  account-service:
    build: ./bank-service
    container_name: account-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://core-db:5432/banking_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: kimquan1
    depends_on:
      - core-db
    networks:
      - banking-network
    healthcheck:
      # Dùng wget gọi vào cổng Actuator để check sức khỏe App
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 5

  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    depends_on:
      - account-service
    networks:
      - banking-network
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 5

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "80:8080"
    depends_on:
      account-service:
        condition: service_healthy
      transaction-service:
        condition: service_healthy
    networks:
      - banking-network

volumes:
  pg-data:

networks:
  banking-network:
    driver: bridge