server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: account-service-route
              uri: http://account-service:8080
              predicates:
                - Path=/api/v1/accounts/**
            - id: transaction-service-route
              uri: http://transaction-service:8080
              predicates:
                - Path=/api/v1/transactions/**