server:
  port: 8080
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    password: kimquan1
    url: jdbc:postgresql://localhost:5432/user_db_test
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true